version: '3'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j:/data
    environment:
      NEO4J_AUTH: neo4j/password
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"